### ISSUE TITLE
QGIS 3 compatibility

### ISSUE THREAD

**Issue by kadarivan** [Christophe55/SwapVectorDirection#4]
The SwapVectorDirection plugin not compatible with QGIS 3.

**Comment by bricofoy** [comment]
> Impossible de charger l'extension 'SwapVectorDirection' provoque une erreur lors de l'appel à sa méthode classFactory() 

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print u"no selected feature")? 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/yann/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection/__init__.py", line 34, in classFactory
    from .SwapVectorDirection import SwapVectorDirection
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/yann/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection/SwapVectorDirection.py", line 209
    print u"no selected feature"
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print u"no selected feature")?


Version de Python : 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
Version de QGIS : 3.0.1-Girona Girona, a86bec2

**Comment by bricofoy** [comment]
Et avec la dernière version disponible ici :

> Impossible de charger l'extension 'SwapVectorDirection-master' provoque une erreur lors de l'appel à sa méthode classFactory() 
> 
> ModuleNotFoundError: No module named 'resources_rc' 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/yann/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection-master/__init__.py", line 34, in classFactory
>     from .SwapVectorDirection import SwapVectorDirection
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/yann/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection-master/SwapVectorDirection.py", line 34, in 
>     import resources_rc
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'resources_rc'
> 
> 
> Version de Python : 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
> Version de QGIS : 3.0.1-Girona Girona, a86bec2 
>

**Comment by Christophe55** [comment]
Le plugin est maintenant débogué et fonctionne sous QGIS 3.2, pas testé sous qgis 3.0, mais il ne devrait pas y avoir de pb.
